name: Count Lines of Code

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
    branches: [development, master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  cloc:
    permissions:
      pull-requests: write
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs djdefi/cloc-action
      - name: Count Lines of Code (cloc)
        uses: djdefi/cloc-action@6
        with:
          options: . --vcs=git --exclude-list-file=./package-lock.json --exclude-dir=e2e-tests --md --report-file=cloc.md
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: cloc.md
          github-token: ${{ secrets.GITHUB_TOKEN }}
