name: End-to-end test
on:
  pull_request:
    paths-ignore: .github/workflows/**
    branches:
      - development
      - master
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    environment: Testing
    steps:
      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          command: npm run e2e-pipeline
          # quote the url to be safe against YML parsing surprises
          wait-on: '${{ secrets.PUBLIC_UI_URL }}, ${{ secrets.PUBLIC_API_URL }}'
        env:
          CYPRESS_baseUrl: ${{ secrets.PUBLIC_UI_URL }}
      - name: Test Recordings
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: e2e-tests/cypress/videos
