name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          command: npm run e2e-pipeline
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:4173'
        env:
          CYPRESS_TEST_USER_EMAIL: ${{secrets.CYPRESS_TEST_USER_EMAIL}}
          CYPRESS_TEST_USER_PASSWORD: ${{secrets.CYPRESS_TEST_USER_PASSWORD}}
          SECRET_BREVO_CLIENT_EMAIL: ${{secrets.SECRET_BREVO_CLIENT_EMAIL}}
          SECRET_BREVO_CLIENT_PASS: ${{secrets.SECRET_BREVO_CLIENT_PASS}}
          CYPRESS_baseUrl: http://localhost:4173
