name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: cd e2e-tests && npm run e2e-pipeline
          build: npm run build
          start: npm start
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:4173'
        env: # Or as an environment variable
          SECRET_BREVO_CLIENT_EMAIL: ${{ secrets.SECRET_BREVO_CLIENT_EMAIL }}
          SECRET_BREVO_CLIENT_PASS: ${{ secrets.SECRET_BREVO_CLIENT_PASS }}
